# Generated by Django 3.2 on 2025-05-20 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_menupermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='menupermission',
            name='email',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='MenuRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.menuitem')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.rol')),
            ],
        ),
        migrations.AddField(
            model_name='menupermission',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.rol'),
        ),
        migrations.AlterUniqueTogether(
            name='menupermission',
            unique_together={('email', 'rol')},
        ),
        migrations.RemoveField(
            model_name='menupermission',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='menupermission',
            name='user',
        ),
    ]
